import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import "../src/styles/GlobalStyles.css";
import { ThemeProvider } from "styled-components";
import { theme } from "../src/styles/themes/MainThemes";
import { GlobalStyles } from "../src/styles/Global";
import Auth from "../components/auth";

const App = ({ Component, pageProps }: any) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <SessionProvider session={pageProps.session}>
        <ThemeProvider theme={theme}>
          <GlobalStyles />
          {Component.auth ? (
            <Auth>
              <Component {...pageProps} />
            </Auth>
          ) : (
            <Component {...pageProps} />
          )}
        </ThemeProvider>
      </SessionProvider>
    </>
  );
};
export default App;
